### PR TITLE
Fix test for the std::nullptr_t case, as it's not a simple string

### PR DESCRIPTION
**Pull request by CraftSpider**
I forgot to fix this test, sorry.
If the rapid-fire PRs are annoying I'll slow down, I just found this and liked it, figured I would try to help improve it for everyone. And I like doing one feature per PR if possible, keeps things clean

### CODE REVIEW

**Comment by whitequark** [comment]
Small PRs are fine, easier to review.

I would prefer if you put the `builtin`/`qual_name` node directly in `_builtin_types` and got rid of `if isinstance(value, list):`. Then the test would work as-is, and the code would be easier to follow.

**Comment by CraftSpider** [comment]
Alright. I just realized how late it is here, so I'll have to do that tomorrow, but thank you for the review.

**Comment by CraftSpider** [comment]
Shoot, pushed the code adding transaction/guard by accident. That was gonna be my next PR, I can separate that out if you want

**Comment by whitequark** [comment]
Let's split

**Comment by CraftSpider** [comment]
Removed extraneous changes

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
