### PR TITLE
Add missing builtin types to the map

### PR DESCRIPTION
**Pull request by CraftSpider**
List of builtins sourced from https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling-builtin
Not sure that the decltype one is perfect AST form, please tell me how I might fix it if not

### CODE REVIEW

**Comment by whitequark** [comment]
Could you rebase please?

**Comment by CraftSpider** [comment]
Rebase complete

**Comment by whitequark** [comment]
Does `decltype(auto)` come up a lot? If not, I'd prefer if we just ditched it for now, since we don't support `decltype` anywhere else. Otherwise it likely needs its own AST node.

**Comment by CraftSpider** [comment]
It doesn't come up in `libstdc++.so`, so I'll remove it for now

**Comment by CraftSpider** [comment]
I'll make a separate pull to add general decltype support if it comes up, but that's not super likely with what I'm working on right now

**Comment by whitequark** [comment]
That's OK, thanks.

**Pull request merged**
